# Generated by Django 5.0 on 2024-01-04 11:57

import django.utils.timezone
import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_bio_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(default=django.utils.timezone.now, upload_to='profiles'),
            preserve_default=False,
        ),
    ]
