# Generated by Django 5.0 on 2024-01-05 12:19

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_bio_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='profiles/no-image.jpeg', null=True, upload_to='profiles/'),
        ),
    ]
