# Generated by Django 5.0 on 2024-01-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coding_stack',
        ),
        migrations.DeleteModel(
            name='CodingStack',
        ),
        migrations.AddField(
            model_name='profile',
            name='coding_stack',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'JavaScript')], max_length=20, null=True),
        ),
    ]
