# Generated by Django 5.0 on 2024-01-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_profile_coding_stack_delete_codingstack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coding_stack',
        ),
        migrations.AddField(
            model_name='profile',
            name='coding_stack',
            field=models.ManyToManyField(blank=True, to='profiles.codingstack'),
        ),
    ]
